"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Sheet, SheetContent, SheetTitle } from "@/components/ui/sheet";
import { AppButton } from "@/components/ui/app-button";
import { AppStoreIcon, PlayStoreIcon } from "@/components/icons/icons";
import { useCustomerAppLinks } from "@/lib/use-customer-app-links";
import { useIsMobile } from "@/lib/use-is-mobile";
import { siteConfig } from "@/lib/site-config";
import { useTranslation } from "@/lib/i18n/translation-context";

const DISMISSED_KEY = "hasOpenedInApp";
const APP_LAUNCH_TIMEOUT_MS = 1500;

/** Shown on `?share=true` links (generated by the mobile app's share sheet) —
 * tries to hand the visitor straight to the native app via its custom URL
 * scheme, preserving the full path *and* query string (lat/lng/lang) that
 * brought them here, then falls back to the store listing if the app isn't
 * installed. Mobile/tablet only — desktop ignores `share=true` entirely. */
export function OpenInAppSheet() {
  const { t } = useTranslation();
  const router = useRouter();
  const isMobile = useIsMobile();
  const { scheme, playStoreUrl, appStoreUrl } = useCustomerAppLinks();

  const [open, setOpen] = useState(false);
  const [showFallback, setShowFallback] = useState(false);
  const [launching, setLaunching] = useState(false);

  const isShare = router.query.share === "true";

  useEffect(() => {
    if (!router.isReady || !isMobile || !isShare) return;
    if (typeof window === "undefined") return;
    if (window.localStorage.getItem(DISMISSED_KEY)) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- one-time gate synced from router readiness + localStorage, not derivable from props/state
    setOpen(true);
  }, [router.isReady, isMobile, isShare]);

  const dismiss = () => {
    window.localStorage.setItem(DISMISSED_KEY, "true");
    setOpen(false);
    setShowFallback(false);
  };

  const handleOpen = () => {
    if (!scheme) {
      setShowFallback(true);
      return;
    }
    setLaunching(true);
    const deeplink = `${scheme}://${window.location.host}${window.location.pathname}${window.location.search}`;
    window.location.href = deeplink;
    window.setTimeout(() => {
      setLaunching(false);
      if (document.visibilityState === "visible") {
        setShowFallback(true);
      } else {
        window.localStorage.setItem(DISMISSED_KEY, "true");
        setOpen(false);
      }
    }, APP_LAUNCH_TIMEOUT_MS);
  };

  if (!isMobile) return null;

  const isIos = typeof navigator !== "undefined" && /iPad|iPhone|iPod/.test(navigator.userAgent);

  return (
    <Sheet open={open} onOpenChange={(next) => !next && dismiss()}>
      <SheetContent
        side="bottom"
        showCloseButton={false}
        className="z-70 flex w-full flex-col gap-4 rounded-t-2xl p-4 lg:hidden"
      >
        <div className="mx-auto h-1 w-10 shrink-0 rounded-3xl bg-bg-inverse/20" />

        {showFallback ? (
          <>
            <SheetTitle className="text-center text-base font-medium text-text-primary">
              {t("openInApp.fallbackTitle", { appName: siteConfig.appName })}
            </SheetTitle>
            <p className="text-center text-sm text-text-secondary">{t("openInApp.fallbackDescription")}</p>
            <div className="flex w-full flex-col items-stretch gap-2">
              {isIos && appStoreUrl ? (
                <a href={appStoreUrl} target="_blank" rel="noopener noreferrer">
                  <AppButton variant="primary" size="md" leftIcon={AppStoreIcon} className="w-full">
                    {t("openInApp.appStore")}
                  </AppButton>
                </a>
              ) : (
                playStoreUrl && (
                  <a href={playStoreUrl} target="_blank" rel="noopener noreferrer">
                    <AppButton variant="primary" size="md" leftIcon={PlayStoreIcon} className="w-full">
                      {t("openInApp.playStore")}
                    </AppButton>
                  </a>
                )
              )}
            </div>
            <AppButton variant="secondary-outline" size="md" className="w-full" onClick={dismiss}>
              {t("openInApp.cancel")}
            </AppButton>
          </>
        ) : (
          <>
            <SheetTitle className="text-center text-base font-medium text-text-primary">
              {t("openInApp.title", { appName: siteConfig.appName })}
            </SheetTitle>
            <p className="text-center text-sm text-text-secondary">{t("openInApp.description")}</p>
            <div className="flex w-full items-center gap-3">
              <AppButton
                variant="secondary-outline"
                size="md"
                className="flex-1"
                disabled={launching}
                onClick={dismiss}
              >
                {t("openInApp.cancel")}
              </AppButton>
              <AppButton variant="primary" size="md" className="flex-1" disabled={launching} onClick={handleOpen}>
                {t("openInApp.open")}
              </AppButton>
            </div>
          </>
        )}
      </SheetContent>
    </Sheet>
  );
}
