import type { ServiceCardData } from "@/lib/mock-data/home-care-services";

export const nearbyServices: ServiceCardData[] = [
  {
    id: "nearby-service-1",
    title: "Kitchen Cleaning",
    image: "https://placehold.co/200x260",
    category: "Home Service",
    rating: 4.8,
    persons: 5,
    minutes: 30,
    price: 70,
    originalPrice: 100,
    discountPercent: 12,
  },
  {
    id: "nearby-service-2",
    title: "Kitchen Cleaning",
    image: "https://placehold.co/200x260",
    category: "Home Service",
    rating: 4.8,
    persons: 5,
    minutes: 30,
    price: 70,
    originalPrice: 100,
    discountPercent: 12,
  },
  {
    id: "nearby-service-3",
    title: "Kitchen Cleaning",
    image: "https://placehold.co/200x260",
    category: "Home Service",
    rating: 4.8,
    persons: 5,
    minutes: 30,
    price: 70,
    originalPrice: 100,
    discountPercent: 12,
  },
  {
    id: "nearby-service-4",
    title: "Kitchen Cleaning",
    image: "https://placehold.co/200x260",
    category: "Home Service",
    rating: 4.8,
    persons: 5,
    minutes: 30,
    price: 70,
    originalPrice: 100,
    discountPercent: 12,
  },
  {
    id: "nearby-service-5",
    title: "Kitchen Cleaning",
    image: "https://placehold.co/200x260",
    category: "Home Service",
    rating: 4.8,
    persons: 5,
    minutes: 30,
    price: 70,
    originalPrice: 100,
    discountPercent: 12,
  },
  {
    id: "nearby-service-6",
    title: "Kitchen Cleaning",
    image: "https://placehold.co/200x260",
    category: "Home Service",
    rating: 4.8,
    persons: 5,
    minutes: 30,
    price: 70,
    originalPrice: 100,
    discountPercent: 12,
  },
];
