// Writes public/sitemap.xsl always, then either pages/sitemap.xml.ts
// (dynamic mode, NEXT_PUBLIC_SEO=true) or public/sitemap.xml (static
// mode, NEXT_PUBLIC_SEO=false) — deleting whichever conflicts, since
// Next.js can't have both a page route and a static file claim the same
// /sitemap.xml URL. Runs automatically via "predev"/"prebuild".
import { existsSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

for (const envFile of [".env.local", ".env"]) {
  try {
    process.loadEnvFile(join(ROOT, envFile));
  } catch {
    // File doesn't exist — fine, try the next one / fall back to process.env as-is.
  }
}

const seoEnabled = process.env.NEXT_PUBLIC_SEO !== "false";

const XSL_CONTENT = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html>
<head>
<title>XML Sitemap</title>
<style>
body { font-family: sans-serif; margin: 2rem; color: #1f2937; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #dedcdd; font-size: 0.875rem; }
th { background: #efeef0; }
a { color: #0b6e4f; text-decoration: none; }
a:hover { text-decoration: underline; }
</style>
</head>
<body>
<h1>XML Sitemap</h1>
<table>
<tr><th>URL</th><th>Priority</th><th>Change Frequency</th><th>Last Modified</th></tr>
<xsl:for-each select="sitemap:urlset/sitemap:url">
<tr>
<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
<td><xsl:value-of select="sitemap:priority"/></td>
<td><xsl:value-of select="sitemap:changefreq"/></td>
<td><xsl:value-of select="sitemap:lastmod"/></td>
</tr>
</xsl:for-each>
</table>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
`;

writeFileSync(join(ROOT, "public", "sitemap.xsl"), XSL_CONTENT);
console.log("[setup-sitemap] wrote public/sitemap.xsl");

const PAGES_SITEMAP_PATH = join(ROOT, "pages", "sitemap.xml.ts");
const PUBLIC_SITEMAP_PATH = join(ROOT, "public", "sitemap.xml");

const DYNAMIC_PAGE_CONTENT = `// Auto-generated by scripts/setup-sitemap.mjs — do not hand-edit.
// Regenerate by re-running the script (it runs automatically via the
// "predev"/"prebuild" npm scripts whenever NEXT_PUBLIC_SEO is "true").
import type { GetServerSideProps } from "next";
import { generateSitemapXml } from "@/lib/sitemap-builder";

export const getServerSideProps: GetServerSideProps = async ({ res }) => {
  const xml = await generateSitemapXml();
  res.setHeader("Content-Type", "application/xml");
  res.write(xml);
  res.end();
  return { props: {} };
};

export default function SitemapXmlPage() {
  return null;
}
`;

if (seoEnabled) {
  if (existsSync(PUBLIC_SITEMAP_PATH)) {
    rmSync(PUBLIC_SITEMAP_PATH);
    console.log("[setup-sitemap] removed stale public/sitemap.xml (SEO on)");
  }
  writeFileSync(PAGES_SITEMAP_PATH, DYNAMIC_PAGE_CONTENT);
  console.log("[setup-sitemap] wrote pages/sitemap.xml.ts (dynamic mode)");
} else {
  if (existsSync(PAGES_SITEMAP_PATH)) {
    rmSync(PAGES_SITEMAP_PATH);
    console.log("[setup-sitemap] removed stale pages/sitemap.xml.ts (SEO off)");
  }
}

const STATIC_ROUTES = [
  "/",
  "/about-us",
  "/become-provider",
  "/blogs",
  "/categories",
  "/contact-us",
  "/custom-page",
  "/faqs",
  "/privacy-policy",
  "/providers",
  "/search",
  "/services",
  "/terms-and-conditions",
];

function escapeXml(value) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function getPriority(route) {
  if (route === "/") return "1.0";
  if (route === "/services" || route === "/providers" || route === "/blogs") return "0.9";
  if (route === "/about-us" || route === "/contact-us") return "0.8";
  return "0.7";
}

function buildStaticSitemapXml(baseUrl) {
  const today = new Date().toISOString().split("T")[0];
  const entries = STATIC_ROUTES.map((route) => {
    const loc = escapeXml(baseUrl + route);
    return `<url><loc>${loc}</loc><lastmod>${today}</lastmod><changefreq>weekly</changefreq><priority>${getPriority(route)}</priority></url>`;
  });
  return `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${entries.join("")}</urlset>`;
}

if (!seoEnabled) {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "";
  writeFileSync(PUBLIC_SITEMAP_PATH, buildStaticSitemapXml(baseUrl));
  console.log("[setup-sitemap] wrote public/sitemap.xml (static mode)");
}
